spring.application.name=uberApp

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSl=false
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

#smtp config
spring.mail.username = paliwaldeep70@gmail.com
spring.mail.password = vnhz zbno fhkm ivyx
spring.mail.host = smtp.gmail.com
spring.mail.port =587

spring.mail.properties.mail.smtp.auto = true
spring.mail.properties.mail.smtp.starttls.enable = true
