spring.application.name=uberApp

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSl=false
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations =classpath:data.sql


#security config
jwt.secretKey=ashfkhsd2k2j4hjhkh545j4hkjhkjh546jkjkk6j5kjh6kjh


